### PR TITLE
Add openid examples

### PR DESCRIPTION
**Pull request by laedit**
Add the OpenID and Steam posts + guides.

Like you said on twitter I have forget that it wasn't OAuth :smiley: 
So I totally understand if you prefer not to have them on the site, or in a special category.

### CODE REVIEW

**Comment by jerriep** [comment]
Awesome Jérémie, thanks for this.

One quick request though before I test on my local machine. Can you please change the image files to use a dash (-) instead of an underscore (_). This is better for SEO (https://www.mattcutts.com/blog/dashes-vs-underscores/)

Also where you use PascalCasing in image names, rather use a dash, and make everything lowercase.

So:

Complete_Registration.png -> complete-registration.png

and 

GoToLoginPage.png -> go-to-login-page.png

Also make sure that wherever you reference the images in the markdown files, that use use the exact lowercase name, as GitHub pages is case sensitive.

I will create a "Contribution" guide on the Wiki explaining this.

Thanks

**Comment by laedit** [comment]
Done, thanks for the tip!

**Comment by jerriep** [comment]
@laedit It is merged Jérémie. Thanks again.

Please make sure your API Key for Steam is revoked (or changed) so no one looking at the docs can use it.

**Comment by laedit** [comment]
Thanks.
No problem, this API Key was revoked long ago.

**Comment by RufusJWB** [comment]
Do you somewhere have an example for OpenID now? It is not really selfexplaining :-(

**Comment by laedit** [comment]
There is a guide on the website: http://www.oauthforaspnet.com/providers/openid/

**Comment by RufusJWB** [comment]
Thank you! I found this example later by myself, but I don't get it to work
in my environment. I created a new issue for this problem.
Am 09.04.2016 06:39 schrieb "Jérémie Bertrand" <notifications@github.com>:

**Pull request merged**
